import { personaCollections } from '../src/data/collections';

export interface ToolDefinition {
  name: string;
  path: string;
  category: string;
  expectsCopyButton: boolean;
}

export interface CollectionDefinition {
  title: string;
  path: string;
  toolCount: number;
}

export const toolDefinitions: ToolDefinition[] = [
  { name: 'JSON Formatter', path: '/json-formatter', category: 'Formatters', expectsCopyButton: true },
  { name: 'INI Formatter', path: '/ini-formatter', category: 'Formatters', expectsCopyButton: false },
  { name: 'HTTP Request Formatter', path: '/http-request-formatter', category: 'Formatters', expectsCopyButton: false },
  { name: 'Stack Trace Formatter', path: '/stack-trace-formatter', category: 'Formatters', expectsCopyButton: false },
  { name: 'XML Formatter', path: '/xml-formatter', category: 'Formatters', expectsCopyButton: true },
  { name: 'HTML Formatter', path: '/html-formatter', category: 'Formatters', expectsCopyButton: true },
  { name: 'CSS Formatter', path: '/css-formatter', category: 'Formatters', expectsCopyButton: true },
  { name: 'Markdown Formatter', path: '/markdown-formatter', category: 'Formatters', expectsCopyButton: true },
  { name: 'Base64 Studio', path: '/base64-studio', category: 'Encoders', expectsCopyButton: true },
  { name: 'Base64 URL Studio', path: '/base64-url-studio', category: 'Encoders', expectsCopyButton: false },
  { name: 'Base58 Studio', path: '/base58-studio', category: 'Encoders', expectsCopyButton: false },
  { name: 'Base32 Studio', path: '/base32-studio', category: 'Encoders', expectsCopyButton: true },
  { name: 'Hash Generator', path: '/hash-generator', category: 'Generators', expectsCopyButton: true },
  { name: 'Case Converter', path: '/case-converter', category: 'Converters', expectsCopyButton: true },
  { name: 'Delimiter Converter', path: '/delimiter-converter', category: 'Converters', expectsCopyButton: false },
  { name: 'Duration Converter', path: '/duration-converter', category: 'Converters', expectsCopyButton: false },
  { name: 'Path Separator Converter', path: '/path-separator-converter', category: 'Converters', expectsCopyButton: false },
  { name: 'Byte Size Converter', path: '/byte-size-converter', category: 'Converters', expectsCopyButton: false },
  { name: 'Color Format Converter', path: '/color-format-converter', category: 'Converters', expectsCopyButton: false },
  { name: 'Line Ending Converter', path: '/line-ending-converter', category: 'Converters', expectsCopyButton: false },
  { name: 'Tabs Spaces Converter', path: '/tabs-spaces-converter', category: 'Converters', expectsCopyButton: false },
  { name: 'List JSON Converter', path: '/list-json-converter', category: 'Converters', expectsCopyButton: true },
  { name: 'Timestamp Converter', path: '/timestamp-converter', category: 'Converters', expectsCopyButton: true },
  { name: 'Number Base Converter', path: '/number-base-converter', category: 'Converters', expectsCopyButton: false },
  { name: 'Roman Numeral Converter', path: '/roman-numeral-converter', category: 'Converters', expectsCopyButton: false },
  { name: 'URL Studio', path: '/url-encoder', category: 'Encoders', expectsCopyButton: true },
  { name: 'Quoted Printable Studio', path: '/quoted-printable-studio', category: 'Encoders', expectsCopyButton: false },
  { name: 'Data URL Studio', path: '/data-url-studio', category: 'Encoders', expectsCopyButton: false },
  { name: 'Basic Auth Studio', path: '/basic-auth-studio', category: 'Encoders', expectsCopyButton: false },
  { name: 'Character Code Studio', path: '/character-code-studio', category: 'Encoders', expectsCopyButton: false },
  { name: 'Password Generator', path: '/password-generator', category: 'Generators', expectsCopyButton: true },
  { name: 'Color Palette Generator', path: '/color-palette-generator', category: 'Generators', expectsCopyButton: false },
  { name: 'Passphrase Generator', path: '/passphrase-generator', category: 'Generators', expectsCopyButton: false },
  { name: 'Nano ID Generator', path: '/nano-id-generator', category: 'Generators', expectsCopyButton: false },
  { name: 'Fake User Generator', path: '/fake-user-generator', category: 'Generators', expectsCopyButton: false },
  { name: 'Random Number Generator', path: '/random-number-generator', category: 'Generators', expectsCopyButton: false },
  { name: 'Username Generator', path: '/username-generator', category: 'Generators', expectsCopyButton: false },
  { name: 'API Token Generator', path: '/api-token-generator', category: 'Generators', expectsCopyButton: false },
  { name: 'Release Note Generator', path: '/release-note-generator', category: 'Generators', expectsCopyButton: false },
  { name: 'Test Case Title Generator', path: '/test-case-title-generator', category: 'Generators', expectsCopyButton: false },
  { name: 'Lorem Ipsum Generator', path: '/lorem-ipsum-generator', category: 'Generators', expectsCopyButton: true },
  { name: 'JWT Decoder', path: '/jwt-decoder', category: 'Security', expectsCopyButton: true },
  { name: 'JWT Expiry Checker', path: '/jwt-expiry-checker', category: 'Security', expectsCopyButton: false },
  { name: 'API Key Fingerprinter', path: '/api-key-fingerprinter', category: 'Security', expectsCopyButton: false },
  { name: 'SRI Hash Generator', path: '/sri-hash-generator', category: 'Security', expectsCopyButton: true },
  { name: 'CORS Policy Inspector', path: '/cors-policy-inspector', category: 'Security', expectsCopyButton: false },
  { name: 'Regex Tester', path: '/regex-tester', category: 'Testers', expectsCopyButton: true },
  { name: 'JSON Pointer Tester', path: '/json-pointer-tester', category: 'Testers', expectsCopyButton: false },
  { name: 'URL Pattern Tester', path: '/url-pattern-tester', category: 'Testers', expectsCopyButton: false },
  { name: 'Semver Range Tester', path: '/semver-range-tester', category: 'Testers', expectsCopyButton: false },
  { name: 'HTTP Status Tester', path: '/http-status-tester', category: 'Testers', expectsCopyButton: false },
  { name: 'Regex Replace Tester', path: '/regex-replace-tester', category: 'Testers', expectsCopyButton: false },
  { name: 'Email Validator', path: '/email-validator', category: 'Testers', expectsCopyButton: false },
  { name: 'QR Code Generator', path: '/qr-code-generator', category: 'Generators', expectsCopyButton: true },
  { name: 'UUID Generator', path: '/uuid-generator', category: 'Generators', expectsCopyButton: true },
  { name: 'ULID Generator', path: '/ulid-generator', category: 'Generators', expectsCopyButton: true },
  { name: 'HMAC Generator', path: '/hmac-generator', category: 'Security', expectsCopyButton: true },
  { name: 'Query String Studio', path: '/query-string-studio', category: 'Converters', expectsCopyButton: true },
  { name: 'HTML Entity Studio', path: '/html-entity-studio', category: 'Encoders', expectsCopyButton: true },
  { name: 'ROT13 Studio', path: '/rot13-studio', category: 'Encoders', expectsCopyButton: true },
  { name: 'Binary Text Studio', path: '/binary-text-studio', category: 'Encoders', expectsCopyButton: true },
  { name: 'Morse Code Studio', path: '/morse-code-studio', category: 'Encoders', expectsCopyButton: true },
  { name: 'Hex Studio', path: '/hex-studio', category: 'Encoders', expectsCopyButton: true },
  { name: 'Slugify Studio', path: '/slugify-studio', category: 'Converters', expectsCopyButton: true },
  { name: 'Unicode Escape Studio', path: '/unicode-escape-studio', category: 'Encoders', expectsCopyButton: true },
  { name: 'CSV JSON Studio', path: '/csv-json-studio', category: 'Converters', expectsCopyButton: true },
  { name: 'Text Diff Checker', path: '/text-diff-checker', category: 'Testers', expectsCopyButton: false },
  { name: 'Docker Optimizer', path: '/docker-optimizer', category: 'Developer', expectsCopyButton: true },
  { name: 'Gitignore Builder', path: '/gitignore-builder', category: 'Developer', expectsCopyButton: false },
  { name: 'Fixture File Generator', path: '/media-fixture-generator', category: 'Developer', expectsCopyButton: false },
  { name: 'Video to GIF Studio', path: '/video-to-gif-studio', category: 'Developer', expectsCopyButton: false },
  { name: 'GitHub Actions Validator', path: '/github-actions-validator', category: 'Testers', expectsCopyButton: false },
  { name: 'Dependency Visualizer', path: '/dependency-visualizer', category: 'Developer', expectsCopyButton: false },
  { name: 'Bundle Size Calculator', path: '/bundle-size-calculator', category: 'Developer', expectsCopyButton: false },
  { name: 'cURL to Code Converter', path: '/curl-to-code-converter', category: 'Developer', expectsCopyButton: true },
  { name: 'SQL Beautifier', path: '/sql-beautifier', category: 'Formatters', expectsCopyButton: true },
  { name: 'Semantic Version Calculator', path: '/semantic-version-calculator', category: 'Developer', expectsCopyButton: false },
  { name: 'Breaking Change Detector', path: '/breaking-change-detector', category: 'Developer', expectsCopyButton: false },
  { name: 'HTTP Header Inspector', path: '/http-header-inspector', category: 'Security', expectsCopyButton: false },
  { name: 'Cookie Security Inspector', path: '/cookie-security-inspector', category: 'Security', expectsCopyButton: false },
  { name: 'CSP Policy Inspector', path: '/csp-policy-inspector', category: 'Security', expectsCopyButton: false },
  { name: 'Security.txt Inspector', path: '/security-txt-inspector', category: 'Security', expectsCopyButton: false },
  { name: 'Open Redirect Checker', path: '/open-redirect-checker', category: 'Security', expectsCopyButton: false },
  { name: 'Password Policy Inspector', path: '/password-policy-inspector', category: 'Security', expectsCopyButton: false },
  { name: 'Signed URL Inspector', path: '/signed-url-inspector', category: 'Security', expectsCopyButton: false },
  { name: 'JSON Path Explorer', path: '/json-path-explorer', category: 'Testers', expectsCopyButton: false },
  { name: 'JSON Value Comparator', path: '/json-value-comparator', category: 'Testers', expectsCopyButton: false },
  { name: 'Header Diff Checker', path: '/header-diff-checker', category: 'Testers', expectsCopyButton: false },
  { name: 'HAR Request Extractor', path: '/har-request-extractor', category: 'Testers', expectsCopyButton: false },
  { name: 'Webhook Payload Inspector', path: '/webhook-payload-inspector', category: 'Testers', expectsCopyButton: false },
  { name: 'SQL Result to Markdown Table', path: '/sql-result-to-markdown-table', category: 'Formatters', expectsCopyButton: true },
  { name: 'Log Level Analyzer', path: '/log-level-analyzer', category: 'Testers', expectsCopyButton: false },
  { name: 'UUID Extractor', path: '/uuid-extractor', category: 'Developer', expectsCopyButton: false },
  { name: 'Link Extractor', path: '/link-extractor', category: 'Developer', expectsCopyButton: false },
  { name: 'Secret Redactor', path: '/secret-redactor', category: 'Security', expectsCopyButton: true },
  { name: 'API Error Formatter', path: '/api-error-formatter', category: 'Formatters', expectsCopyButton: true },
  { name: 'Cron Expression Explainer', path: '/cron-expression-explainer', category: 'Developer', expectsCopyButton: false },
  { name: 'Docker Compose Auditor', path: '/docker-compose-auditor', category: 'Developer', expectsCopyButton: false },
  { name: 'OpenAPI Summary', path: '/openapi-summary', category: 'Developer', expectsCopyButton: false },
  { name: 'JSON Lines Studio', path: '/json-lines-studio', category: 'Developer', expectsCopyButton: true },
  { name: 'ENV File Inspector', path: '/env-file-inspector', category: 'Security', expectsCopyButton: false },
  { name: 'ANSI Escape Cleaner', path: '/ansi-escape-cleaner', category: 'Formatters', expectsCopyButton: true },
  { name: 'Markdown Checklist Builder', path: '/markdown-checklist-builder', category: 'Formatters', expectsCopyButton: true },
  { name: 'Line Deduplicator', path: '/line-deduplicator', category: 'Developer', expectsCopyButton: true },
  { name: 'Markdown Studio', path: '/markdown-studio', category: 'Formatters', expectsCopyButton: true },
  { name: 'Markdown Table Builder', path: '/markdown-table-builder', category: 'Formatters', expectsCopyButton: true },
  { name: 'JSON Schema Generator', path: '/json-schema-generator', category: 'Developer', expectsCopyButton: true },
  { name: 'Shift Handover Builder', path: '/shift-handover-builder', category: 'Developer', expectsCopyButton: true },
  {
    name: 'Pressure Drop & Head Loss Calculator',
    path: '/pressure-drop-head-loss-calculator',
    category: 'Converters',
    expectsCopyButton: false,
  },
  { name: 'Drawing Revision Diff Checker', path: '/drawing-revision-diff-checker', category: 'Testers', expectsCopyButton: true },
  { name: 'Tolerance Stack-Up Analyzer', path: '/tolerance-stackup-analyzer', category: 'Testers', expectsCopyButton: true },
  { name: 'BOM Diff Checker', path: '/bom-diff-checker', category: 'Testers', expectsCopyButton: true },
  { name: 'Hole/Shaft Fit Calculator', path: '/hole-shaft-fit-calculator', category: 'Converters', expectsCopyButton: false },
  { name: 'Mechanical Formula Finder', path: '/mechanical-formula-finder', category: 'Developer', expectsCopyButton: true },
  { name: 'Prompt Studio', path: '/prompt-studio', category: 'AI', expectsCopyButton: true },
  { name: 'Prompt Diff Checker', path: '/prompt-diff-checker', category: 'AI', expectsCopyButton: false },
  { name: 'Prompt Test Runner', path: '/prompt-test-runner', category: 'AI', expectsCopyButton: false },
  { name: 'Prompt Eval Scorecard', path: '/prompt-eval-scorecard', category: 'AI', expectsCopyButton: false },
  { name: 'Structured Output Schema Builder', path: '/structured-output-schema-builder', category: 'AI', expectsCopyButton: true },
  { name: 'Output Repair Studio', path: '/output-repair-studio', category: 'AI', expectsCopyButton: true },
  { name: 'Jailbreak / Prompt Injection Checker', path: '/jailbreak-prompt-injection-checker', category: 'AI', expectsCopyButton: false },
  { name: 'Hallucination Review Workspace', path: '/hallucination-review-workspace', category: 'AI', expectsCopyButton: false },
  { name: 'RAG Chunk Previewer', path: '/rag-chunk-previewer', category: 'AI', expectsCopyButton: false },
  { name: 'Embedding Similarity Explorer', path: '/embedding-similarity-explorer', category: 'AI', expectsCopyButton: false },
  { name: 'System Prompt Builder', path: '/system-prompt-builder', category: 'AI', expectsCopyButton: true },
  { name: 'Few-shot Example Organizer', path: '/few-shot-example-organizer', category: 'AI', expectsCopyButton: true },
  { name: 'Prompt Variable Extractor', path: '/prompt-variable-extractor', category: 'AI', expectsCopyButton: false },
  { name: 'Token / Cost Estimator', path: '/token-cost-estimator', category: 'AI', expectsCopyButton: false },
  { name: 'Latency vs Quality Planner', path: '/latency-quality-planner', category: 'AI', expectsCopyButton: false },
  { name: 'AI Response Comparator', path: '/ai-response-comparator', category: 'AI', expectsCopyButton: false },
  { name: 'Safety Policy Tester', path: '/safety-policy-tester', category: 'AI', expectsCopyButton: false },
  { name: 'Tool Call Payload Validator', path: '/tool-call-payload-validator', category: 'AI', expectsCopyButton: false },
  { name: 'Function Calling Schema Tester', path: '/function-calling-schema-tester', category: 'AI', expectsCopyButton: false },
  { name: 'Agent Loop Trace Viewer', path: '/agent-loop-trace-viewer', category: 'AI', expectsCopyButton: false },
  { name: 'Grounded Answer Checker', path: '/grounded-answer-checker', category: 'AI', expectsCopyButton: true },
  { name: 'Citation Formatter for AI Answers', path: '/citation-formatter-for-ai-answers', category: 'AI', expectsCopyButton: true },
  { name: 'Conversation State Simulator', path: '/conversation-state-simulator', category: 'AI', expectsCopyButton: false },
  { name: 'Context Window Compactor', path: '/context-window-compactor', category: 'AI', expectsCopyButton: false },
  { name: 'Prompt Leak Detector', path: '/prompt-leak-detector', category: 'AI', expectsCopyButton: false },
  { name: 'Consistency Runner', path: '/consistency-runner', category: 'AI', expectsCopyButton: false },
  { name: 'Best-of-N Comparison Tool', path: '/best-of-n-comparison-tool', category: 'AI', expectsCopyButton: false },
  { name: 'Batch Eval Dataset Builder', path: '/batch-eval-dataset-builder', category: 'AI', expectsCopyButton: true },
  { name: 'Synthetic Test Case Generator', path: '/synthetic-test-case-generator', category: 'AI', expectsCopyButton: false },
  { name: 'Red Team Scenario Builder', path: '/red-team-scenario-builder', category: 'AI', expectsCopyButton: false },
];

export const generators = toolDefinitions
  .filter((tool) => tool.category === 'Generators')
  .map((tool) => tool.name);

export const collectionDefinitions: CollectionDefinition[] = personaCollections.map((collection) => ({
  title: collection.title,
  path: collection.path,
  toolCount: collection.toolIds.length,
}));
