export interface ToolDefinition {
  name: string;
  path: string;
  category: string;
  expectsCopyButton: boolean;
}

export const toolDefinitions: ToolDefinition[] = [
  { name: 'JSON Formatter', path: '/json-formatter', category: 'Formatters', expectsCopyButton: true },
  { name: 'Base64 Studio', path: '/base64-studio', category: 'Encoders', expectsCopyButton: true },
  { name: 'Hash Generator', path: '/hash-generator', category: 'Generators', expectsCopyButton: true },
  { name: 'Case Converter', path: '/case-converter', category: 'Converters', expectsCopyButton: true },
  { name: 'Timestamp Converter', path: '/timestamp-converter', category: 'Converters', expectsCopyButton: true },
  { name: 'URL Studio', path: '/url-encoder', category: 'Encoders', expectsCopyButton: true },
  { name: 'Password Generator', path: '/password-generator', category: 'Generators', expectsCopyButton: true },
  { name: 'JWT Decoder', path: '/jwt-decoder', category: 'Security', expectsCopyButton: true },
  { name: 'Regex Tester', path: '/regex-tester', category: 'Testers', expectsCopyButton: true },
  { name: 'QR Code Generator', path: '/qr-code-generator', category: 'Generators', expectsCopyButton: true },
  { name: 'UUID Generator', path: '/uuid-generator', category: 'Generators', expectsCopyButton: true },
  { name: 'ULID Generator', path: '/ulid-generator', category: 'Generators', expectsCopyButton: true },
  { name: 'HMAC Generator', path: '/hmac-generator', category: 'Security', expectsCopyButton: true },
  { name: 'Query String Studio', path: '/query-string-studio', category: 'Converters', expectsCopyButton: true },
  { name: 'HTML Entity Studio', path: '/html-entity-studio', category: 'Encoders', expectsCopyButton: true },
  { name: 'Hex Studio', path: '/hex-studio', category: 'Encoders', expectsCopyButton: true },
  { name: 'Slugify Studio', path: '/slugify-studio', category: 'Converters', expectsCopyButton: true },
  { name: 'Unicode Escape Studio', path: '/unicode-escape-studio', category: 'Encoders', expectsCopyButton: true },
  { name: 'CSV JSON Studio', path: '/csv-json-studio', category: 'Converters', expectsCopyButton: true },
  { name: 'Text Diff Checker', path: '/text-diff-checker', category: 'Testers', expectsCopyButton: false },
  { name: 'Docker Optimizer', path: '/docker-optimizer', category: 'Developer', expectsCopyButton: true },
  { name: 'GitHub Actions Validator', path: '/github-actions-validator', category: 'Developer', expectsCopyButton: false },
  { name: 'Dependency Visualizer', path: '/dependency-visualizer', category: 'Developer', expectsCopyButton: false },
  { name: 'Bundle Size Calculator', path: '/bundle-size-calculator', category: 'Developer', expectsCopyButton: false },
  { name: 'cURL to Code Converter', path: '/curl-to-code-converter', category: 'Developer', expectsCopyButton: true },
  { name: 'SQL Beautifier', path: '/sql-beautifier', category: 'Developer', expectsCopyButton: true },
  { name: 'Semantic Version Calculator', path: '/semantic-version-calculator', category: 'Developer', expectsCopyButton: false },
  { name: 'Breaking Change Detector', path: '/breaking-change-detector', category: 'Developer', expectsCopyButton: false },
  { name: 'HTTP Header Inspector', path: '/http-header-inspector', category: 'Developer', expectsCopyButton: false },
  { name: 'Cron Expression Explainer', path: '/cron-expression-explainer', category: 'Developer', expectsCopyButton: false },
  { name: 'Docker Compose Auditor', path: '/docker-compose-auditor', category: 'Developer', expectsCopyButton: false },
  { name: 'OpenAPI Summary', path: '/openapi-summary', category: 'Developer', expectsCopyButton: false },
  { name: 'Markdown Table Builder', path: '/markdown-table-builder', category: 'Developer', expectsCopyButton: true },
  { name: 'JSON Schema Generator', path: '/json-schema-generator', category: 'Developer', expectsCopyButton: true },
  { name: 'Prompt Studio', path: '/prompt-studio', category: 'AI', expectsCopyButton: true },
  { name: 'Prompt Diff Checker', path: '/prompt-diff-checker', category: 'AI', expectsCopyButton: false },
  { name: 'Prompt Test Runner', path: '/prompt-test-runner', category: 'AI', expectsCopyButton: false },
  { name: 'Prompt Eval Scorecard', path: '/prompt-eval-scorecard', category: 'AI', expectsCopyButton: false },
  { name: 'Structured Output Schema Builder', path: '/structured-output-schema-builder', category: 'AI', expectsCopyButton: true },
  { name: 'Output Repair Studio', path: '/output-repair-studio', category: 'AI', expectsCopyButton: true },
  { name: 'Jailbreak / Prompt Injection Checker', path: '/jailbreak-prompt-injection-checker', category: 'AI', expectsCopyButton: false },
  { name: 'Hallucination Review Workspace', path: '/hallucination-review-workspace', category: 'AI', expectsCopyButton: false },
  { name: 'RAG Chunk Previewer', path: '/rag-chunk-previewer', category: 'AI', expectsCopyButton: false },
  { name: 'Embedding Similarity Explorer', path: '/embedding-similarity-explorer', category: 'AI', expectsCopyButton: false },
  { name: 'System Prompt Builder', path: '/system-prompt-builder', category: 'AI', expectsCopyButton: true },
  { name: 'Few-shot Example Organizer', path: '/few-shot-example-organizer', category: 'AI', expectsCopyButton: true },
  { name: 'Prompt Variable Extractor', path: '/prompt-variable-extractor', category: 'AI', expectsCopyButton: false },
  { name: 'Token / Cost Estimator', path: '/token-cost-estimator', category: 'AI', expectsCopyButton: false },
  { name: 'Latency vs Quality Planner', path: '/latency-quality-planner', category: 'AI', expectsCopyButton: false },
  { name: 'AI Response Comparator', path: '/ai-response-comparator', category: 'AI', expectsCopyButton: false },
  { name: 'Safety Policy Tester', path: '/safety-policy-tester', category: 'AI', expectsCopyButton: false },
  { name: 'Tool Call Payload Validator', path: '/tool-call-payload-validator', category: 'AI', expectsCopyButton: false },
  { name: 'Function Calling Schema Tester', path: '/function-calling-schema-tester', category: 'AI', expectsCopyButton: false },
  { name: 'Agent Loop Trace Viewer', path: '/agent-loop-trace-viewer', category: 'AI', expectsCopyButton: false },
  { name: 'Grounded Answer Checker', path: '/grounded-answer-checker', category: 'AI', expectsCopyButton: true },
  { name: 'Citation Formatter for AI Answers', path: '/citation-formatter-for-ai-answers', category: 'AI', expectsCopyButton: true },
  { name: 'Conversation State Simulator', path: '/conversation-state-simulator', category: 'AI', expectsCopyButton: false },
  { name: 'Context Window Compactor', path: '/context-window-compactor', category: 'AI', expectsCopyButton: false },
  { name: 'Prompt Leak Detector', path: '/prompt-leak-detector', category: 'AI', expectsCopyButton: false },
  { name: 'Consistency Runner', path: '/consistency-runner', category: 'AI', expectsCopyButton: false },
  { name: 'Best-of-N Comparison Tool', path: '/best-of-n-comparison-tool', category: 'AI', expectsCopyButton: false },
  { name: 'Batch Eval Dataset Builder', path: '/batch-eval-dataset-builder', category: 'AI', expectsCopyButton: true },
  { name: 'Synthetic Test Case Generator', path: '/synthetic-test-case-generator', category: 'AI', expectsCopyButton: false },
  { name: 'Red Team Scenario Builder', path: '/red-team-scenario-builder', category: 'AI', expectsCopyButton: false },
];

export const generators = toolDefinitions
  .filter((tool) => tool.category === 'Generators')
  .map((tool) => tool.name);
