import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const publicDir = path.join(root, 'public');
const adsTxtPath = path.join(publicDir, 'ads.txt');
const generatedMarker = '# Generated by scripts/prepare-adsense.mjs';
const adsTxtLine = process.env.VITE_ADSENSE_ADS_TXT_LINE?.trim();

if (!fs.existsSync(publicDir)) {
  fs.mkdirSync(publicDir, { recursive: true });
}

if (!adsTxtLine) {
  if (fs.existsSync(adsTxtPath)) {
    const current = fs.readFileSync(adsTxtPath, 'utf8');
    if (current.includes(generatedMarker)) {
      fs.rmSync(adsTxtPath);
      console.log('Removed generated public/ads.txt because VITE_ADSENSE_ADS_TXT_LINE is not set.');
    }
  }
  process.exit(0);
}

const contents = `${generatedMarker}\n${adsTxtLine}\n`;
fs.writeFileSync(adsTxtPath, contents, 'utf8');
console.log('Prepared public/ads.txt from VITE_ADSENSE_ADS_TXT_LINE.');
